



Terms & conditions
 Acceptance of Terms
 Welcome to Ico's Academy. By reading and continuing to use our site you (“You” or “Your) agree to the following Terms of Use (“ToU”) and to our Privacy Policy. This website is operated by GGO LTD. (“Ico's Academy”, “we” “us” “our”), Buzludzha 29, 1606 Sofia, Bulgariа. These Terms of Use govern, and constitute an Agreement between you and us regarding, your use of EagleCrypto.com and all other websites operated by us, including websites dedicated to our Consensus and Construct conferences, any mobile applications operated or approved by us and any other communication tools including e-mail or any other content delivery method (collectively, the “Ico's Academy Sites”). We reserve the right at any time to:
Change the terms and conditions of the ToU; Change all or any portion of the Ico's Academy Sites, including eliminating or discontinuing any content or feature of the Ico's Academy Sites; or Change other conditions for use of the Ico's Academy Sites including fees or other changes for Research (with reasonable notice, in our sole discretion). Any changes we make to the ToU will be effective immediately after we post the modified ToU on WWW.ICOS.ACADEMY
Content on the Ico's Academy's Sites
All of the information and other content displayed on, transmitted through, or used in connection with the Ico's Academy Sites, including for example, advertising, directories, guides, articles, opinions, reviews, text, photographs, images, illustrations, audio clips, video, html, source and object code, software, data, the selection and arrangement of the aforementioned and the "look and feel" of the Ico's Academy Sites (collectively, the "Content"), are protected under applicable copyrights and other proprietary (including but not limited to intellectual property) rights and are the intellectual property of Ico's Academy, and its affiliated companies, licensors and suppliers. Ico's Academy actively protects its rights to the Content to the fullest extent of the law.
You may use the Content online and solely for your personal, non-commercial use, and you may download or print a single copy of any portion of the Content for your personal, non-commercial use, provided you do not remove any trademark, copyright or other notice contained in such Content. You may not, for example, republish the Content on any Internet, Intranet or Extranet site or incorporate the Content in any database, compilation, archive or cache or store the Content in electronic form on your computer or mobile device unless otherwise expressly permitted by Ico's Academy. You may not distribute any of the Content to others, whether or not for payment or other consideration, and you may not modify, copy, frame, reproduce, sell, publish, transmit, display or otherwise use any portion of the Content, except as permitted by the ToU or by securing the prior written consent of Ico's Academy.
The Content includes logotypes, trademarks and service marks (collectively "Marks") owned by Ico's Academy, and Marks owned by other information providers and third parties. For example, "Ico's Academy" is a registered trademark of Ico's Academy, Inc. No Marks may be used in any manner unless approved in advance, in writing by Ico's Academy.
Requests to use the Content for any purpose other than as permitted in the ToU should be submitted to Admin@icos. academy.
Infringement Complaints
Ico's Academy respects the intellectual property of others. If you believe that your work has been copied in a way that constitutes copyright infringement or are aware of any infringing material placed by any third party on the Website, please contact our designated copyright agent, in writing, either by email at support@icos.academy or by First Class mail at GGO LTD, 27 Tsar Aleksandar st, ap 1, Sofia district Sofia, Bulgaria, 1309, Attn: Copyright Agent, and provide the following information as required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act
A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; Identification of the copyright work claimed to have been infringed; Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to locate the material; Information sufficient to permit us to contact the complaining party, including address, telephone number, and e-mail address; A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
Disclaimer of Warranty and Limitation of Liability
The information, products and services on the Ico's Academy Sites are provided on a strictly “as is,” “where is” and “where available” basis. Ico's Academy does not provide any warranties (either express or implied) with respect to the information provided on any Ico's Academy site and/or your use of any of the Ico's Academy Sites generally or for any particular purpose. Ico's Academy expressly disclaims any implied warranties, including but not limited to, warranties of title, non-infringement, merchantability or fitness for a particular purpose. Ico's Academy will not be responsible for any loss or damage that could result from interception by third parties of any information made available to you via the Ico's Academy Sites or any of them. Although the information provided to you on this website is obtained or compiled from sources we believe to be reliable, Ico's Academy cannot and does not guarantee the accuracy, validity, timeliness, or completeness of any information or data made available to you for any particular purpose. Neither Ico's Academy, nor any of its affiliates, directors, officers or employees, nor any third party providers of content, software and/or technology (collectively, the “Ico's Academy parties”), will be liable or have any responsibility of any kind for any loss or damage that you incur in the event of any failure or interruption of any Ico's Academy site, or resulting from the act or omission of any other party involved in making any Ico's Academy site, the data contained therein or the products or services offered thereby available to you, or from any other cause relating to your access to, inability to access, or use of any Ico's Academy site or the materials contained therein, whether or not the circumstances giving rise to such cause may have been within the control of Ico's Academy or of any vendor providing software or services.
In no event will Ico's Academy or any of the Ico's Academy parties be liable to you, whether in contract or tort, for any direct, special, indirect, consequential or incidental damages or any other damages of any kind even if Ico's Academy or any other such party has been advised of the possibility thereof. This limitation on liability includes, but is not limited to, the transmission of any viruses which may infect a user’s equipment, failure of mechanical or electronic equipment or communication lines, telephone or other interconnect problems (e.g., you cannot access your internet service provider), unauthorized access, theft, operator errors, strikes or other labor problems or any force majeure. Ico's Academy cannot and does not guarantee continuous, uninterrupted or secure access to any of the Ico's Academy Sites.
Content Disclaimer
All writers; and experts; opinions are their own and do not constitute financial advice in any way whatsoever. Nothing published by Ico's Academy constitutes an investment recommendation, nor should any data or Content published by Ico's Academy be relied upon for any investment activities.
YOUR USE OF THIS SERVICE IS AT YOUR OWN RISK. THIS SERVICE AND ALL THE MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICES AND OTHER CONTENT IN THIS SERVICE ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, GGO LTD DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. GGO LTD DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THIS SERVICE WILL BE AVAILABLE, UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED OR THAT GGO LTD'S WEBSITES OR THE SERVERS THAT MAKE THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. GGO LTD DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE MATERIAL, INFORMATION, SOFTWARE, FACILITIES, SERVICES OR OTHER CONTENT IN THIS SERVICE OR ANY SITES LINKED TO THIS SERVICE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. GGO LTD MAKES NO WARRANTIES THAT YOUR USE OF THE MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICE OR OTHER CONTENT IN THIS SERVICE WILL NOT INFRINGE THE RIGHTS OF OTHERS AND GGO LTD ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ERRORS OR OMISSIONS IN SUCH MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICE OR OTHER CONTENT OF THIS SERVICE. IF APPLICABLE LAW DOES NOT ALLOW THE EXCLUSION OF SOME OR ALL OF THE ABOVE IMPLIED WARRANTIES TO APPLY TO YOU, THE ABOVE EXCLUSIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.
Ico's Academy strongly recommends that you perform your own independent research and/or speak with a qualified investment professional before making any financial decisions.
Contents of Educational Packages
A description of the Services is available on our Website under our Education Page. We will provide the Services with reasonable care and skill in accordance with the description set out on the Website. All lessons are one-on-one with a member of our Education or Success teams.
We reserve the right to vary or withdraw any of the Services described on the Website without notice.
We expect you to confirm that the Services you are purchasing will meet your needs. We do not make any guarantee to you that you will obtain a particular result, professional qualification or successful investments. All information is designed to enable our clients to be able to invest independently or mine independently, results may vary. We will not give specific investment advice. All software mentioned in the courses is free third party software. At the moment we do not offer any software, all software is given as a general recommendation, we make no guarantee as to the results and do not offer any warrantee for the software. A course instructor or member of our Support team can assist you with installing and using third-party mining software, however we do not guarantee any results.
Registration
All online courses are offered on a non-credit basis. As these courses are open to the general public, there are no prerequisites; however, students must be at least 18 years of age and have access to a computer with high speed Internet in order to register.
Payment
Payment in full is required at the time of registration. All course tuition is billed in US dollars, Euros or Canadian dollars; your financial institutions may charge a fee for conversion to local currency. Payment may be made by BitCoin, Ethereum, BitPay, UPayCard, MasterCard, or Visa.
Refund Policy
Ico's Academy offers you a fair 30 Days Money Back Guarantee.
This is one of the most comprehensive refund guarantees available for online purchases. After assisting thousands of satisfied customers, we know we can offer our customers this amazing refund policy because we are so confident that you are going to be happy with our products and services.
Simply put, if you are unhappy with your purchase of Ico's Academy, we will issue you a complete refund if you have:
* Contacted our dedicated customer support team asking for assistance if required
* Submitted your request for a refund within 30 days of making your purchase
* Provided a valid reason for requesting a return within 30 days of purchase
* Provided a valid report that the charge was fraudulent or unauthorized
You may submit a refund request by sending an email to compliance@icos.academy.
Once you have completed this return process please allow 2-5 business days for our customer support team to reply to your request. We will contact you to confirm either your refund has been processed or ask for additional details should they need any.
Please Note - Any consumer who is deemed to be abusing our Consumer Promise may have their right to return revoked and may also be blocked from making future purchases through our platform. Once a refund / cancellation request has been processed, all services provided will be terminated and we will request an immediate return of all products purchased.
How Will You Be Refunded?
* You will be refunded via the method that you purchased.
* Please allow 7-10 days for refunds to appear in your credit card/bank account.
If you have questions regarding this policy or any other terms in this agreement:
Should you need to speak with a member of our team regarding your purchase, they can be contacted on the relevant email addresses here: support@icos.academy.
Links to other sites
Certain links, including hypertext links, in our site will take you to external websites. These are provided for your convenience and inclusion of any link does not imply endorsement or approval by Ico's Academy of the linked site, its operator or its content. Each of those websites have their own "Terms and Conditions." We are not responsible for the content of any website outside of the Ico's Academy Sites. We do not monitor and assume no duty to monitor the content of any such third-party websites.
Use of cookies
Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site. These cookies are used to collect information about how visitors use our site. We use the information to compile reports and to help us improve the site. The cookies collect information in an anonymous form, including the number of visitors to the site, where visitors have come to the site from and the pages they visited.
By using our website, you agree that we can place these types of cookies on your device.
DISCLAIMER OF WARRANTIES:
We support third party software. We do not take responsibility for any of the software and do not guarantee any results. All purchases on the site or over the phone are for Technical Support, Training and Educational Services. We do not charge for any use of Software, however we may charge for technical support services including installation and software training.
Right of Access under the Processing of Personal Data (Protection of the Individual) Law of 2001, as amended or replaced form time to time, you as a natural person have the right to obtain a copy of any personal information which we hold about you and to advise us of any perceived inaccuracy. To make a request, please contact us, verifying your identity and specifying what information you require. You may contact us via e-mail at support@icos.academy.
All purchases are final, if you have a question about a purchase, please contact our support team through the live chat feature on the site, via telephone at *PLEASE INSERT NUMBER or via Email at support@icos.academy. Our support team will answer all inquiries, however any type of refund request must be made in writing and will be reviewed within 5 business days by our finance department, which will approve or deny each request on a case by case basis. Please note that any request for a refund must be made within 24 hours of the initial purchase, or before the services purchased have been received.
LIMITATION OF LIABILITY:
GGO LTD DOES NOT ACCEPT ANY LIABILITY FOR ANY LOSS OR DAMAGE (DIRECT, INDIRECT, PUNATIVE, ACTUAL, CONSEQUENTIAL, INCIDENTAL, SPECIAL, EXEMPLARY OR OTHERWISE) RESULTING FROM ANY USE OF, OR INABILITY TO USE, THIS SERVICE OR THE MATERIAL, INFORMATION, SOFTWARE, FACILITIES, SERVICES OR OTHER CONTENT ON THIS SERVICE, REGARDLESS OF THE BASIS UPON WHICH LIABILITY IS CLAIMED AND EVEN IF GGO LTD HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE. WITHOUT LIMITATION, YOU (AND NOT GGO LTD) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION IN THE EVENT OF ANY SUCH LOSS OR DAMAGE ARISING. IF APPLICABLE LAW DOES NOT ALLOW ALL OR ANY PART OF THE ABOVE LIMITATION OF LIABILITY TO APPLY TO YOU, THE LIMITATIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.
CHOICE OF LAW
The ToU and the agreement formed hereby (“Agreement”) shall be governed by, and construed and enforced in accordance with, the laws of the Republic of Bulgaria, without regard to conflicts of law provisions. Unless otherwise agreed in writing by you and us, any dispute arising out of or relating to the Agreement, or the breach hereof, shall be finally resolved by arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, or such arbitration body as required by law, rule or regulation, and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction. The arbitration will be conducted in the English language before a single arbitrator in the Republic of Bulgaria, Republic of Bulgaria. Such arbitration must be commenced within one (1) year after the claim or cause of action arises. If for any reason any provision of this Agreement, or a portion thereof, shall be unenforceable, that provision shall be enforced to the maximum extent permissible so as to effect the intent of this Agreement, and the remainder of this Agreement shall continue in full force and effect. This Agreement constitutes the entire agreement between us and you with respect to the Ico's Academy Sites and it supersedes all prior or contemporaneous communications, agreements and understandings between us and you with respect to the subject matter hereof. A printed version of this Agreement shall be admissible in judicial or administrative proceedings.

Contact
admin@icos.academy
Any rights not expressly granted herein are reserved. © 2017 GGO LTD.
Updated on September 14, 2017


GGO LTD (“Ico's Academy”)
Privacy and Safeguarding of Client Information Policy
For Internal and External Distribution
1.0 Overview
Ico's Academy is a brand managed and operated by GGO LTD.
PRIVACY POLICY Last updated on August 10th, 2017
1. Our Commitment to You We understand the importance of maintaining the confidentiality and privacy of Your Information. By entrusting us with your information, we would like to assure you of our commitment to keep such information private. We have taken measurable steps to protect the confidentiality, security and integrity of Your Information.
2. Collection of Information If you decide to apply to open an account with us and hence become our Client there is certain information that we will require from you in order to do so. We and our affiliates may collect Your Information directly from you or. This information includes, but is not limited to personal details such as name, address, date of birth, and contact details, payment details. We may also collect Your Information in regards to your use of our website(s), such as pages visited, frequency, duration of visit and trading activities. From time to time we may also request further information to help us improve our Service to you (if you are our Client) or our activities under our relevant Agreement, as the case may be, or comply with Applicable Regulations.
3. Use of the Information We will use, store, process and handle Your Personal Information (in case you are a natural person) in connection with the furthering of the Agreement between us, in accordance to the Processing of Personal Data (Protection of the Individual) Law of 2001, as amended or replaced form time to time. Your Information (not in the public domain or already possessed by us without a duty of confidentiality) which we hold is to be treated by us as confidential and will not be used for any purpose other than in connection with the provision, administration and improvement of our Services to you or the furthering of our Agreement between us, establishing and managing your account or a relationship between us, reviewing your ongoing needs, enhancing customer service and products, giving you ongoing information or opportunities that we believe may be relevant to you, improving our relationship, anti-money laundering and due diligence checks, for research and statistical purposes and for marketing purposes (according to the Agreement between us), as applicable. By entering an Agreement with us (to become our Client), you will be consenting to the transmittal of Your Personal Information according to the provisions of Processing of Personal Data (Protection of the Individual) Law of 2001.
4. We may contact you, for the purpose of administering the terms of our Agreement between us, from time to time, make direct contact with you by telephone, fax, email, or post. If you agree, we or any of our Affiliates of the Company or any other company in our group, may make contact with you from time to time, by telephone, fax, email or post for marketing purposes to bring to your attention products or services that may be of interest to you or to conduct market research.
5. Disclosure of Information under the Agreement between us, we have the right to disclose Your Information (including recordings and documents of a confidential nature, card details) in certain circumstances. According to the Agreement between us, Your Information may be disclosed: (a) where required by law or a court order by a competent Court; or any other regulatory authority having control or jurisdiction over us or you or our associates or in whose territory we have Clients or Providers, as applicable; (c) to relevant authorities to investigate or prevent fraud, money laundering or other illegal activity. To do so they may check the details you supplied against any particulars on any database (public or otherwise) to which they have access. They may also use your details in the future to assist other companies for verification purposes. A record of the search will be retained by us; (f) to our professional advisors provided that in each case the relevant professional shall be informed about the confidential nature of such information and commit to the confidentiality herein obligations as well; (g) to other service providers who create, maintain or process databases (whether electronic or not), offer record keeping services, email transmission services, messaging services or similar services which aim to assist us collect, storage, process and use Your Information or get in touch with you or improve the provision of our Services or activities under the Agreement between us; (h) to data reporting service providers; (i) to other service providers for statistical purposes in order to improve our marketing, in such a case, the data will be provided in an aggregate form; (j) to market research call centers that provide telephone or email surveys with the purpose to improve our Services or activities, but only contact details; (k) where necessary in order for us to defend or exercise our legal rights to any court or tribunal or arbitrator or governmental authority, as the case may be; (l) at your request or with your consent; (m) to our Affiliates or any other company in our group; (n) to our employees so as to exercise their duties to further the Agreement between us, or to assure the efficient functioning of our Platform, the Automatic Orders and the Trading Data functions.
6. Safeguard Measures Your Information is stored on secure servers. We limit access of Your Information only to those employees or partners that need to know the information in order to enable the carrying out of the Agreement between us. We have procedures in place regarding how to safeguard and use Your Information, for example by requesting our Affiliates and employees to maintain the confidentiality of Your Information. We will not keep Your Information for any longer than is required. In many cases, information must be kept for considerable periods of time. Retention periods will be determined taking into account the type of information that is collected and the purpose for which it is collected, bearing in mind the requirements applicable to the situation and the need to destroy outdated, unused information at the earliest reasonable time. While we will use all reasonable efforts to safeguard Your Information, you acknowledge that the use of the internet is not entirely secure and for this reason we cannot guarantee the security or integrity of any personal data transferred from you, or to you via the internet.
7. Change of Information You may inform the Company at any time that Your Information has changed or that you wish the Company to delete information we hold about you by emailing us at support@icos.academy. We will change or delete Your Information in accordance to your instructions, except to the extent that we are required to hold Your Information for regulatory or legal purposes, to provide you with the Services you have requested or to maintain adequate business records.
8. If you have any questions regarding this policy, wish to access or change your information or have a complaint, or if you have any questions about security on our Website, you may email us at support@icos.academy.
9. Update of this Policy This Policy is subject to change without notice. For this reason, you are advised to look for updates from time to time.



